repos:
- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.2.5
  hooks:
  - id: prettier
    additional_dependencies: ['prettier@3.2.5']
    files: "\.(js|ts|tsx|jsx)$"
